force-app/main/default/objects/APEX_Job_Shweta__c/APEX_Job_Shweta__c.object-meta.xml
<CustomObject>
    <description>Information about job profile....</description>
    <label>Job_Shweta</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job_Shweta Name1</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job_Shwetas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_JobPositins__c.field-meta.xml
<CustomField>
    <fullName>APEX_JobPositins__c</fullName>
    <label>JobPositins</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_Manager__c.field-meta.xml
<CustomField>
    <fullName>APEX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job_Shwetas</relationshipLabel>
    <relationshipName>Job_Shwetas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_Name__c.field-meta.xml
<CustomField>
    <fullName>APEX_Name__c</fullName>
    <displayFormat>JOB-{000}</displayFormat>
    <label>Name</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_NoOfPosition__c.field-meta.xml
<CustomField>
    <fullName>APEX_NoOfPosition__c</fullName>
    <label>NoOfPosition</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MyClass.cls
global with sharing class MyClass {
   public String accountName { get; set; }
    public static Account account { get; set; }
    public MyClass() { } // empty constructor
    
    @RemoteAction
    global static Account getAccount(String accountName) {
        account = [SELECT Id, Name, Phone, Type, NumberOfEmployees 
                   FROM Account WHERE Name = :accountName];
        return account;
    }
}
    
 /*   public static APEX_Job_Shweta__c objJob { get; set; }
    public MyClass() { } // empty constructor
    
   @RemoteAction
    global static void increaseNoOfPosition(){
        APEX_Job_Shweta__c objJob=[SELECT Id, APEX_Name__c, APEX_NoOfPosition__c,APEX_JobPositins__c,APEX_Manager__c FROM APEX_Job_Shweta__c WHERE id=:'a015g00000L58Qt'];
        objJob.APEX_NoOfPosition__c=objJob.APEX_NoOfPosition__c+1;
        update objJob;
        objJob=new APEX_Job_Shweta__c();
    }*/