force-app/main/default/objects/APEX_Job_Shweta__c/APEX_Job_Shweta__c.object-meta.xml
<CustomObject>
    <description>Information about job profile....</description>
    <label>Job_Shweta</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job_Shweta Name1</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job_Shwetas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_ExpireOn__c.field-meta.xml
<CustomField>
    <fullName>APEX_ExpireOn__c</fullName>
    <label>ExpireOn</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/JobScchedularR.cls
global class JobScchedularR implements schedulable{
    global void execute(SchedulableContext ctx){
        List<APEX_Job_Shweta__c> lstJob = new List<APEX_Job_Shweta__c>();
        for(APEX_Job_Shweta__c objJob:[SELECT Id, APEX_ExpireOn__c, APEX_Active__c FROM APEX_Job_Shweta__c WHERE APEX_ExpireOn__c<TODAY]){
            objJob.APEX_Active__c=false;
           
            lstJob.add(objJob);
        }
        Database.update(lstJob);
    }
 }