force-app/main/default/objects/APEX_Job_Shweta__c/APEX_Job_Shweta__c.object-meta.xml
<CustomObject>
    <description>Information about job profile....</description>
    <label>Job_Shweta</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job_Shweta Name1</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job_Shwetas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_ApplicantCout__c.field-meta.xml
<CustomField>
    <fullName>APEX_ApplicantCout__c</fullName>
    <label>ApplicantCout</label>
    <summaryFilterItems>
        <field>Candidate_Shweta__c.APEX_Status__c</field>
        <operation>equals</operation>
        <value>Applied</value>
    </summaryFilterItems>
    <summaryForeignKey>Candidate_Shweta__c.APEX_JOB_Shwetajob__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_ExpireOn__c.field-meta.xml
<CustomField>
    <fullName>APEX_ExpireOn__c</fullName>
    <label>ExpireOn</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_JobPositins__c.field-meta.xml
<CustomField>
    <fullName>APEX_JobPositins__c</fullName>
    <label>JobPositins</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_Manager__c.field-meta.xml
<CustomField>
    <fullName>APEX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job_Shwetas</relationshipLabel>
    <relationshipName>Job_Shwetas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_Name__c.field-meta.xml
<CustomField>
    <fullName>APEX_Name__c</fullName>
    <displayFormat>JOB-{000}</displayFormat>
    <label>Name</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_NoOfPosition__c.field-meta.xml
<CustomField>
    <fullName>APEX_NoOfPosition__c</fullName>
    <label>NoOfPosition</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_SalaryOffered__c.field-meta.xml
<CustomField>
    <fullName>APEX_SalaryOffered__c</fullName>
    <label>SalaryOffered</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/getAllJobs.cls
public class getAllJobs{
  public ApexPages.StandardSetController setCon {
        get {
            if(setCon == null) {
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                    [
                     SELECT APEX_Name__c, APEX_SalaryOffered__c,APEX_Active__c, APEX_ExpireOn__c,
                     APEX_NoOfPosition__c,APEX_ApplicantCout__c,
                     APEX_JobPositins__c, APEX_Manager__c FROM APEX_Job_Shweta__c where id='a015g00000LWrdF'
                     
                    ]
                ));
            }
            return setCon;
        }
        set;
    }
    // Initialize setCon and return a list of records
    public List<APEX_Job_Shweta__c> getOpportunities() {
        return (List<APEX_Job_Shweta__c>) setCon.getRecords();
        
        
    }


}