force-app/main/default/objects/APEX_Job_Shweta__c/APEX_Job_Shweta__c.object-meta.xml
<CustomObject>
    <description>Information about job profile....</description>
    <label>Job_Shweta</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job_Shweta Name1</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job_Shwetas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_ExpireOn__c.field-meta.xml
<CustomField>
    <fullName>APEX_ExpireOn__c</fullName>
    <label>ExpireOn</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchToScheduleExpireOnJob.cls
public class BatchToScheduleExpireOnJob implements Database.Batchable<SObject> {
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator('SELECT id, APEX_ExpireOn__c, APEX_Active__c FROM APEX_Job_Shweta__c');
            }
    
    public void execute(Database.BatchableContext bc, List<APEX_Job_Shweta__c> subLstJob){
        for(APEX_Job_Shweta__c objJob:subLstJob){
            if(objJob.APEX_ExpireOn__c<Date.today()){
                objJob.APEX_Active__c=false;
            }
         }
          Update subLstJob;
    }
    public void finish(Database.BatchableContext bc){
        System.debug('All job Scheduled successfully');
    }
}