force-app/main/default/objects/APEX_Job_Shweta__c/APEX_Job_Shweta__c.object-meta.xml
<CustomObject>
    <description>Information about job profile....</description>
    <label>Job_Shweta</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job_Shweta Name1</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job_Shwetas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_JobPositins__c.field-meta.xml
<CustomField>
    <fullName>APEX_JobPositins__c</fullName>
    <label>JobPositins</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_Manager__c.field-meta.xml
<CustomField>
    <fullName>APEX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job_Shwetas</relationshipLabel>
    <relationshipName>Job_Shwetas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_Name__c.field-meta.xml
<CustomField>
    <fullName>APEX_Name__c</fullName>
    <displayFormat>JOB-{000}</displayFormat>
    <label>Name</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_NoOfPosition__c.field-meta.xml
<CustomField>
    <fullName>APEX_NoOfPosition__c</fullName>
    <label>NoOfPosition</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/Candidate_Shweta__c.object-meta.xml
<CustomObject>
    <description>Information about Candidates...</description>
    <label>Candidate_Shweta</label>
    <nameField>
        <displayFormat>Candidate-{0000}</displayFormat>
        <label>Candidate_Shweta Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate_Shwetas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_ApplicationDate__c.field-meta.xml
<CustomField>
    <fullName>APEX_ApplicationDate__c</fullName>
    <label>ApplicationDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_DateOFBirth__c.field-meta.xml
<CustomField>
    <fullName>APEX_DateOFBirth__c</fullName>
    <label>DateOFBirth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_Email__c.field-meta.xml
<CustomField>
    <fullName>APEX_Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_ExpectedSalary__c.field-meta.xml
<CustomField>
    <fullName>APEX_ExpectedSalary__c</fullName>
    <label>ExpectedSalary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_FirstName__c.field-meta.xml
<CustomField>
    <fullName>APEX_FirstName__c</fullName>
    <label>FirstName</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_FullName__c.field-meta.xml
<CustomField>
    <fullName>APEX_FullName__c</fullName>
    <formula>TEXT(APEX_Salutation__c) &amp;  APEX_FirstName__c &amp;  APEX_LastName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FullName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_JOB_Shwetajob__c.field-meta.xml
<CustomField>
    <fullName>APEX_JOB_Shwetajob__c</fullName>
    <label>Job_Shwetajob</label>
    <referenceTo>APEX_Job_Shweta__c</referenceTo>
    <relationshipLabel>Candidate_Shwetas</relationshipLabel>
    <relationshipName>Candidate_Shwetas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_LastName__c.field-meta.xml
<CustomField>
    <fullName>APEX_LastName__c</fullName>
    <label>LastName</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_Salutation__c.field-meta.xml
<CustomField>
    <fullName>APEX_Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
            </value>
            <value>
                <fullName>Ms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_State__c.field-meta.xml
<CustomField>
    <fullName>APEX_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>Christmas Island</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Gujrat</fullName>
            </value>
            <value>
                <fullName>Madhyapradesh</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/allJobs.cls
global with sharing class allJobs {
    public id jobId{get;set;}
    public APEX_Job_Shweta__c objJob1{get;set;}
    public Candidate_Shweta__c candidate1{get;set;}
    public APEX_Job_Shweta__c jobObj{get;set;}
    
    public List<Candidate_Shweta__c> records{get;set;}
    
    public List<String> fields{get;set;}
    Public Boolean ShowCandidateListFlag{get;set;}
    Public List<Candidate_Shweta__c> accRec{get;set;}
    
    public allJobs(){
          candidate1 = new  Candidate_Shweta__c();
         jobId= ApexPages.CurrentPage().getParameters().get('id');
        accRec = [select name,id, APEX_FullName__c, APEX_ApplicationDate__c, APEX_State__c,APEX_Email__c,APEX_JOB_Shwetajob__c,Country__c,APEX_ExpectedSalary__c FROM Candidate_Shweta__c limit 5];
        ShowCandidateListFlag = false;
        if(jobId!=null){
         jobObj=[SELECT APEX_Name__c, APEX_NoOfPosition__c,APEX_JobPositins__c,APEX_Manager__c FROM APEX_Job_Shweta__c WHERE id=:jobId];
        
        records= [Select APEX_Salutation__c,APEX_FirstName__c,APEX_LastName__c,APEX_FullName__c,APEX_DateOFBirth__c,APEX_ApplicationDate__c,APEX_Email__c,Country__c,APEX_State__c,APEX_ExpectedSalary__c,APEX_JOB_Shwetajob__c FROM Candidate_Shweta__c WHERE APEX_JOB_Shwetajob__c=:jobId];
        
        /* fields = new List<String>{'APEX_Salutation__c', 'APEX_FirstName__c','APEX_LastName__c','APEX_FullName__c','APEX_DateOFBirth__c','APEX_ApplicationDate__c','APEX_Email__c','Country__c','APEX_State__c','APEX_ExpectedSalary__c','APEX_JOB_Shwetajob__c'};*/
        fields = new List<String>{'APEX_FullName__c','APEX_Email__c','id'};
            }
            }
    @RemoteAction
    global static list<APEX_Job_Shweta__c> increaseNoOfPosition(String jobId){
        System.debug('In REMOTE Action Method'+jobid);
       list<APEX_Job_Shweta__c> appliedJob=[SELECT APEX_NoOfPosition__c FROM APEX_Job_Shweta__c WHERE id=:jobId];
        
        System.debug('increase hhsbsxbj='+appliedJob);
        for(APEX_Job_Shweta__c objJob:appliedJob){
           objJob.APEX_NoOfPosition__c=objJob.APEX_NoOfPosition__c+1; 
        }
        Database.SaveResult[] result=Database.update(appliedJob, false);
        return appliedJob;
    }
  
    
    public void Save()
    {
        insert  candidate1;
        candidate1=new Candidate_Shweta__c();
        
    }
    
    
    Public void ShowCandidateMethod(){
        ShowCandidateListFlag = true;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /*  public ApexPages.StandardSetController setCon {
get{
if(setCon==null){
setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
[SELECT APEX_Name__c, APEX_NoOfPosition__c,APEX_JobPositins__c,APEX_Manager__c FROM APEX_Job_Shweta__c ]));
}
return setCon;
}
set;
}

public List<APEX_Job_Shweta__c> getOpportunities(){

return (List<APEX_Job_Shweta__c > )setCon.getRecords();

}*/
    
    
}