force-app/main/default/objects/APEX_Job_Shweta__c/APEX_Job_Shweta__c.object-meta.xml
<CustomObject>
    <description>Information about job profile....</description>
    <label>Job_Shweta</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job_Shweta Name1</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job_Shwetas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_ExpireOn__c.field-meta.xml
<CustomField>
    <fullName>APEX_ExpireOn__c</fullName>
    <label>ExpireOn</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_JobPositins__c.field-meta.xml
<CustomField>
    <fullName>APEX_JobPositins__c</fullName>
    <label>JobPositins</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_Manager__c.field-meta.xml
<CustomField>
    <fullName>APEX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job_Shwetas</relationshipLabel>
    <relationshipName>Job_Shwetas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_NoOfPosition__c.field-meta.xml
<CustomField>
    <fullName>APEX_NoOfPosition__c</fullName>
    <label>NoOfPosition</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/testInactiveJob.cls
@isTest
public class testInactiveJob {
    @testSetup
    static void setUp(){
        Contact contact = new Contact(LastName='Bari');
        insert contact;
        List<APEX_Job_Shweta__c> lstJob=new List<APEX_Job_Shweta__c>();
        lstJob.add(new APEX_Job_Shweta__c(APEX_ExpireOn__c=System.today(),APEX_JobPositins__c='Admin',APEX_NoOfPosition__c=5,APEX_Manager__c=contact.Id));
        lstJob.add(new APEX_Job_Shweta__c(APEX_ExpireOn__c=System.today(),APEX_JobPositins__c='Manager',APEX_NoOfPosition__c=6,APEX_Manager__c=contact.Id));
        lstJob.add(new APEX_Job_Shweta__c(APEX_ExpireOn__c=System.today(),APEX_JobPositins__c='Admin',APEX_NoOfPosition__c=7,APEX_Manager__c=contact.Id));
        insert lstJob;
    }
    
  /*  String CRON_Exp='0 0 0 3 9 ? 2022';
  	 List<APEX_Job_Shweta__c> lstJob=[SELECT Id, Status_c, APEX_ExpireOn__c FROM APEX_Job_Shweta__c WHERE APEX_ExpireOn__c<TODAY];
  	 String jobId=System.Schedulable('Apex Test ' CRON_Exp, new JobScchedularR());
    System.assertEquals(CRON_EXP,ct.CronExpression);
    System.assertEquals(0.ct.TimesTriggered);
    System.assertEquals('2022-09-03 00:00:00', String.valueOf(ct.NextFireTime));
  	 */
   
    

}