force-app/main/default/objects/APEX_Job_Shweta__c/APEX_Job_Shweta__c.object-meta.xml
<CustomObject>
    <description>Information about job profile....</description>
    <label>Job_Shweta</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job_Shweta Name1</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job_Shwetas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_JobPositins__c.field-meta.xml
<CustomField>
    <fullName>APEX_JobPositins__c</fullName>
    <label>JobPositins</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_Manager__c.field-meta.xml
<CustomField>
    <fullName>APEX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job_Shwetas</relationshipLabel>
    <relationshipName>Job_Shwetas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APEX_Job_Shweta__c/fields/APEX_NoOfPosition__c.field-meta.xml
<CustomField>
    <fullName>APEX_NoOfPosition__c</fullName>
    <label>NoOfPosition</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/Candidate_Shweta__c.object-meta.xml
<CustomObject>
    <description>Information about Candidates...</description>
    <label>Candidate_Shweta</label>
    <nameField>
        <displayFormat>Candidate-{0000}</displayFormat>
        <label>Candidate_Shweta Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate_Shwetas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_ApplicationDate__c.field-meta.xml
<CustomField>
    <fullName>APEX_ApplicationDate__c</fullName>
    <label>ApplicationDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_Email__c.field-meta.xml
<CustomField>
    <fullName>APEX_Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_ExpectedSalary__c.field-meta.xml
<CustomField>
    <fullName>APEX_ExpectedSalary__c</fullName>
    <label>ExpectedSalary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_FirstName__c.field-meta.xml
<CustomField>
    <fullName>APEX_FirstName__c</fullName>
    <label>FirstName</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_JOB_Shwetajob__c.field-meta.xml
<CustomField>
    <fullName>APEX_JOB_Shwetajob__c</fullName>
    <label>Job_Shwetajob</label>
    <referenceTo>APEX_Job_Shweta__c</referenceTo>
    <relationshipLabel>Candidate_Shwetas</relationshipLabel>
    <relationshipName>Candidate_Shwetas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_LastName__c.field-meta.xml
<CustomField>
    <fullName>APEX_LastName__c</fullName>
    <label>LastName</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_State__c.field-meta.xml
<CustomField>
    <fullName>APEX_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>Christmas Island</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Gujrat</fullName>
            </value>
            <value>
                <fullName>Madhyapradesh</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_Status__c.field-meta.xml
<CustomField>
    <fullName>APEX_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobTriggerHandlerTestClass.cls
@isTest
public class JobTriggerHandlerTestClass {
    @testSetup
    static void inserDataForTest1(){
    Contact contact=new Contact(Lastname='Kanoja');
    insert contact;
    
    List<APEX_Job_Shweta__c> lstJob=new  List<APEX_Job_Shweta__c>();
    lstJob.add(new APEX_Job_Shweta__c(APEX_JobPositins__c='Developer', APEX_Active__c=false, APEX_NoOfPosition__c=5, APEX_Manager__c=contact.Id));
    lstJob.add(new APEX_Job_Shweta__c(APEX_JobPositins__c='Admin', APEX_Active__c=True, APEX_NoOfPosition__c=3, APEX_Manager__c=contact.Id));
    Database.insert(lstJob);
    
    List<Candidate_Shweta__c> lstCandidate= new  List<Candidate_Shweta__c>();
    lstCandidate.add(new Candidate_Shweta__c(APEX_FirstName__c='shweta1', APEX_LastName__c='Karande1',
                                             Country__c='India', APEX_State__c='Maharashtra', 	APEX_ApplicationDate__c=Date.today().addDays(-6), APEX_Status__c='Applied', APEX_Email__c='sbk@gmail.com', 	
                                             APEX_ExpectedSalary__c=50, APEX_JOB_Shwetajob__c=lstJob[1].Id));

    lstCandidate.add(new Candidate_Shweta__c(APEX_FirstName__c='shweta2', APEX_LastName__c='Karande2',
                                             Country__c='India', APEX_State__c='Maharashtra', APEX_ApplicationDate__c=Date.today().addDays(-6), APEX_Status__c='Applied', APEX_Email__c='sbk@gmail.com', 	
                                             APEX_ExpectedSalary__c=null, APEX_JOB_Shwetajob__c=lstJob[0].Id));
    Database.insert(lstCandidate, false);
    }
    
 @isTest
    public static void checkStatus()
    {
         List<APEX_Job_Shweta__c> listJob =[SELECT APEX_Active__c  ,Id FROM APEX_Job_Shweta__c];
        
        for(APEX_Job_Shweta__c jobList: listJob)
        {
            Database.deleteResult result = Database.delete(jobList.Id);
            System.assertEquals(false,!result.isSuccess());
        }
    
       
    	
        
    }
    
    
     

}