force-app/main/default/objects/Candidate_Shweta__c/Candidate_Shweta__c.object-meta.xml
<CustomObject>
    <description>Information about Candidates...</description>
    <label>Candidate_Shweta</label>
    <nameField>
        <displayFormat>Candidate-{0000}</displayFormat>
        <label>Candidate_Shweta Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate_Shwetas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_ApplicationDate__c.field-meta.xml
<CustomField>
    <fullName>APEX_ApplicationDate__c</fullName>
    <label>ApplicationDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_DateOFBirth__c.field-meta.xml
<CustomField>
    <fullName>APEX_DateOFBirth__c</fullName>
    <label>DateOFBirth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_Email__c.field-meta.xml
<CustomField>
    <fullName>APEX_Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_ExpectedSalary__c.field-meta.xml
<CustomField>
    <fullName>APEX_ExpectedSalary__c</fullName>
    <label>ExpectedSalary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_FirstName__c.field-meta.xml
<CustomField>
    <fullName>APEX_FirstName__c</fullName>
    <label>FirstName</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_FullName__c.field-meta.xml
<CustomField>
    <fullName>APEX_FullName__c</fullName>
    <formula>TEXT(APEX_Salutation__c) &amp;  APEX_FirstName__c &amp;  APEX_LastName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FullName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_JOB_Shwetajob__c.field-meta.xml
<CustomField>
    <fullName>APEX_JOB_Shwetajob__c</fullName>
    <label>Job_Shwetajob</label>
    <referenceTo>APEX_Job_Shweta__c</referenceTo>
    <relationshipLabel>Candidate_Shwetas</relationshipLabel>
    <relationshipName>Candidate_Shwetas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_LastName__c.field-meta.xml
<CustomField>
    <fullName>APEX_LastName__c</fullName>
    <label>LastName</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_Salutation__c.field-meta.xml
<CustomField>
    <fullName>APEX_Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
            </value>
            <value>
                <fullName>Ms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_State__c.field-meta.xml
<CustomField>
    <fullName>APEX_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>Christmas Island</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Gujrat</fullName>
            </value>
            <value>
                <fullName>Madhyapradesh</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomControllerCandidate.cls
public class CustomControllerCandidate{
public Candidate_Shweta__c candidate1{get;set;}
    public id candidateId{get;set;}
     public CustomControllerCandidate()
     {
         candidate1 = new  Candidate_Shweta__c();
         candidateId= ApexPages.CurrentPage().getParameters().get('id');
         if(candidateId!=null)
         {
             candidate1=[Select Id, APEX_Salutation__c,APEX_FirstName__c,APEX_LastName__c,APEX_FullName__c,APEX_DateOFBirth__c,APEX_ApplicationDate__c,APEX_Email__c,Country__c,APEX_State__c,APEX_ExpectedSalary__c,APEX_JOB_Shwetajob__c FROM Candidate_Shweta__c where Id =:candidateId];
		}
     }
    
    public void Save()
    {
        insert  candidate1;
        candidate1=new Candidate_Shweta__c();
    
    }
  
    public void updateMe()
    {
        System.debug(candidate1);
        update  candidate1;
        candidate1=new  Candidate_Shweta__c();
    
    }
  
}