force-app/main/default/objects/Candidate_Shweta__c/Candidate_Shweta__c.object-meta.xml
<CustomObject>
    <description>Information about Candidates...</description>
    <label>Candidate_Shweta</label>
    <nameField>
        <displayFormat>Candidate-{0000}</displayFormat>
        <label>Candidate_Shweta Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate_Shwetas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_Email__c.field-meta.xml
<CustomField>
    <fullName>APEX_Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Candidate_Shweta__c/fields/APEX_Status__c.field-meta.xml
<CustomField>
    <fullName>APEX_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmailCandidatePDFHandler.cls
public class EmailCandidatePDFHandler {
    
       public static void sendEmailToHiredCandidateDetailPDF(List<Candidate_Shweta__c> lstCandidate){
        for(Candidate_Shweta__c objCandidate:lstCandidate){
            if(objCandidate.APEX_Status__c=='Hired' && objCandidate.APEX_Email__c!=null){
              //  SendEmail.SentToCandidate(objCandidate.Id);
            }
        }
        
    }

}